server:
  port: 8085

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Manisha1230/micro-serviceConfiguration.git
          clone-on-start: true
        bootstrap: true
      enabled: true

  application:
    name: Config-Server

